language: php
php:            # When adding or removing php versions to test,
  - 5.5         # make sure the number of tested versions is 
  - 5.6         # updated in:
  - hhvm        # .scrutinizer.yml (tools: external_code_coverage: runs:)
  
install:
  - composer install --no-interaction   # no-interaction will automatically create a default config

script:
  - phpunit -c app/ --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
